import {useEffect,useState} from "react";
import {Plus,Save,Trash2,RefreshCw} from "lucide-react";
import {supabase} from "../lib/supabase";

type Section={id:string;section_type:string;title:string;subtitle:string;content:Record<string,any>;sort_order:number;is_active:boolean};

const empty={section_type:"hero",title:"",subtitle:"",content:"{}",sort_order:"0",is_active:true};

function Form({initial,onDone,onCancel}:{initial?:Section;onDone:()=>void;onCancel:()=>void}){
 const [f,setF]=useState(initial?{section_type:initial.section_type,title:initial.title,subtitle:initial.subtitle,content:JSON.stringify(initial.content||{},null,2),sort_order:String(initial.sort_order),is_active:initial.is_active}:empty);
 const [msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setMsg("");let content:any;try{content=JSON.parse(f.content||"{}")}catch{setMsg("Content must be valid JSON.");return}if(!content||Array.isArray(content)||typeof content!=="object"){setMsg("Content JSON must be an object.");return}const sortOrder=Number(f.sort_order);if(!Number.isInteger(sortOrder)||sortOrder<0){setMsg("Sort order must be a non-negative whole number.");return}const sectionType=f.section_type.trim().toLowerCase();if(!["hero","intro","categories","products","deals","guides","custom"].includes(sectionType)){setMsg("Choose a valid section type.");return}setBusy(true);const row={section_type:sectionType,title:f.title.trim(),subtitle:f.subtitle.trim(),content,sort_order:sortOrder,is_active:f.is_active,updated_at:new Date().toISOString()};const q=initial?supabase.from("homepage_sections").update(row).eq("id",initial.id):supabase.from("homepage_sections").insert(row);const {error}=await q;if(error)setMsg(error.message);else onDone();setBusy(false)};
 return <div className="modal-backdrop"><form className="product-form" onSubmit={submit}><div className="form-head"><div><span className="eyebrow">Homepage section</span><h2>{initial?"Edit section":"Add section"}</h2></div></div><div className="form-grid"><label>Section type<select value={f.section_type} onChange={e=>setF({...f,section_type:e.target.value})}><option value="hero">Hero</option><option value="intro">Intro</option><option value="categories">Categories</option><option value="products">Products</option><option value="deals">Deals</option><option value="guides">Guides</option><option value="custom">Custom</option></select></label><label>Sort order<input type="number" value={f.sort_order} onChange={e=>setF({...f,sort_order:e.target.value})}/></label><label className="wide">Title<input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label className="wide">Subtitle<textarea value={f.subtitle} onChange={e=>setF({...f,subtitle:e.target.value})}/></label><label className="wide">Content JSON<textarea rows={8} value={f.content} onChange={e=>setF({...f,content:e.target.value})}/><small>Optional structured content for future section-specific controls.</small></label></div><div className="checks"><label><input type="checkbox" checked={f.is_active} onChange={e=>setF({...f,is_active:e.target.checked})}/> Active</label></div>{msg&&<div className="notice">{msg}</div>}<div className="form-actions"><button type="button" className="btn" onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy}><Save size={15}/> {busy?"Saving...":"Save section"}</button></div></form></div>
}

export default function AdminHomepageSections(){
 const [rows,setRows]=useState<Section[]>([]),[editing,setEditing]=useState<Section>(),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("homepage_sections").select("*").order("sort_order").order("created_at");if(error)setMsg(error.message);setRows((data||[]) as Section[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const close=()=>{setCreating(false);setEditing(undefined)};
 const remove=async(id:string)=>{if(!confirm("Delete this homepage section?"))return;const {error}=await supabase.from("homepage_sections").delete().eq("id",id);if(error)setMsg(error.message);else load()};
 const toggle=async(r:Section)=>{setMsg("");const {error}=await supabase.from("homepage_sections").update({is_active:!r.is_active,updated_at:new Date().toISOString()}).eq("id",r.id);if(error)setMsg(error.message);else load()};
 const move=async(r:Section,delta:number)=>{const ordered=[...rows].sort((a,b)=>a.sort_order-b.sort_order||a.id.localeCompare(b.id));const index=ordered.findIndex(x=>x.id===r.id);const next=ordered[index+delta];if(!next){setMsg(delta<0?"Already at the top.":"Already at the bottom.");return}const first=await supabase.from("homepage_sections").update({sort_order:next.sort_order,updated_at:new Date().toISOString()}).eq("id",r.id);if(first.error){setMsg(first.error.message);return}const second=await supabase.from("homepage_sections").update({sort_order:r.sort_order,updated_at:new Date().toISOString()}).eq("id",next.id);if(second.error){setMsg(second.error.message);return}load()}
 return <section className="admin-page" style={{display:"block",minHeight:"auto"}}><div className="admin-toolbar"><div><span className="eyebrow">Homepage control</span><h1>Homepage sections</h1><p>Manage optional live sections without inventing content. Empty database means the existing Affinova design stays visible.</p></div><div style={{display:"flex",gap:8}}><button className="btn" onClick={load} disabled={loading}><RefreshCw size={14}/> Reload</button><button className="btn primary" onClick={()=>setCreating(true)}><Plus size={14}/> Add section</button></div></div>{msg&&<div className="notice">{msg}</div>}{loading?<div className="notice">Loading...</div>:!rows.length?<div className="admin-empty">No custom homepage sections yet. The current homepage design remains active.</div>:<div className="admin-table"><table><thead><tr><th>Type</th><th>Title</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{r.section_type}</td><td><strong>{r.title||"Untitled"}</strong><small>{r.subtitle}</small></td><td>{r.sort_order}</td><td><span className={r.is_active?"status good":"status"}>{r.is_active?"Active":"Hidden"}</span></td><td><div className="row-actions"><button className="btn small" onClick={()=>move(r,-1)} disabled={i===0}>↑</button><button className="btn small" onClick={()=>move(r,1)} disabled={i===rows.length-1}>↓</button><button className="btn small" onClick={()=>toggle(r)}>{r.is_active?"Hide":"Activate"}</button><button className="btn small" onClick={()=>setEditing(r)}>Edit</button><button className="icon-danger" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}{(creating||editing)&&<Form initial={editing} onDone={()=>{close();load()}} onCancel={close}/>}</section>
}
