import {useEffect,useState} from "react";
import {supabase} from "./lib/supabase";
import type {Product} from "./types";
import {ExternalLink,LogIn,Plus,Save,ShieldCheck,Trash2,X} from "lucide-react";

type Form={title:string;slug:string;short_description:string;description:string;price:string;original_price:string;currency:string;rating:string;review_count:string;image_url:string;affiliate_url:string;brand:string;is_featured:boolean;is_deal:boolean;is_active:boolean;is_sample:boolean};
const empty:Form={title:"",slug:"",short_description:"",description:"",price:"",original_price:"",currency:"USD",rating:"0",review_count:"0",image_url:"",affiliate_url:"",brand:"",is_featured:false,is_deal:false,is_active:true,is_sample:false};

function ProductForm({initial,onSaved,onCancel}:{initial?:Product;onSaved:()=>void;onCancel:()=>void}){
 const [f,setF]=useState<Form>(initial?{title:initial.title,slug:initial.slug,short_description:initial.short_description||"",description:initial.description||"",price:String(initial.price),original_price:initial.original_price?String(initial.original_price):"",currency:initial.currency,rating:String(initial.rating),review_count:String(initial.review_count),image_url:initial.image_url||"",affiliate_url:initial.affiliate_url||"",brand:initial.brand||"",is_featured:initial.is_featured,is_deal:initial.is_deal,is_active:initial.is_active,is_sample:initial.is_sample}:empty);
 const [busy,setBusy]=useState(false);const [msg,setMsg]=useState("");
 const set=(k:keyof Form,v:string|boolean)=>setF(x=>({...x,[k]:v}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMsg("");const row={title:f.title,slug:f.slug,short_description:f.short_description||null,description:f.description||null,price:Number(f.price),original_price:f.original_price?Number(f.original_price):null,currency:f.currency,rating:Number(f.rating)||0,review_count:Number(f.review_count)||0,image_url:f.image_url||null,affiliate_url:f.affiliate_url||null,brand:f.brand||null,is_featured:f.is_featured,is_deal:f.is_deal,is_active:f.is_active,is_sample:f.is_sample};const q=initial?supabase.from("products").update(row).eq("id",initial.id):supabase.from("products").insert(row);const {error}=await q;if(error)setMsg(error.message);else onSaved();setBusy(false)};
 return <div className="modal-backdrop"><form className="product-form" onSubmit={submit}><div className="form-head"><div><span className="eyebrow">{initial?"Edit":"New"} product</span><h2>{initial?"Update product":"Add product"}</h2></div><button type="button" className="close" onClick={onCancel}><X/></button></div><div className="form-grid"><label>Title<input required value={f.title} onChange={e=>set("title",e.target.value)}/></label><label>Slug<input required value={f.slug} onChange={e=>set("slug",e.target.value)}/></label><label>Price<input required type="number" step="0.01" value={f.price} onChange={e=>set("price",e.target.value)}/></label><label>Original price<input type="number" step="0.01" value={f.original_price} onChange={e=>set("original_price",e.target.value)}/></label><label>Currency<input value={f.currency} onChange={e=>set("currency",e.target.value.toUpperCase())}/></label><label>Brand<input value={f.brand} onChange={e=>set("brand",e.target.value)}/></label><label>Rating<input type="number" min="0" max="5" step=".1" value={f.rating} onChange={e=>set("rating",e.target.value)}/></label><label>Review count<input type="number" min="0" value={f.review_count} onChange={e=>set("review_count",e.target.value)}/></label><label className="wide">Image URL<input value={f.image_url} onChange={e=>set("image_url",e.target.value)} placeholder="https://..."/></label><label className="wide">AliExpress affiliate URL<input value={f.affiliate_url} onChange={e=>set("affiliate_url",e.target.value)} placeholder="https://s.click.aliexpress.com/..."/></label><label className="wide">Short description<textarea value={f.short_description} onChange={e=>set("short_description",e.target.value)}/></label><label className="wide">Description<textarea rows={5} value={f.description} onChange={e=>set("description",e.target.value)}/></label></div><div className="checks"><label><input type="checkbox" checked={f.is_featured} onChange={e=>set("is_featured",e.target.checked)}/> Featured</label><label><input type="checkbox" checked={f.is_deal} onChange={e=>set("is_deal",e.target.checked)}/> Deal</label><label><input type="checkbox" checked={f.is_active} onChange={e=>set("is_active",e.target.checked)}/> Active</label><label><input type="checkbox" checked={f.is_sample} onChange={e=>set("is_sample",e.target.checked)}/> Sample</label></div>{msg&&<div className="notice">{msg}</div>}<div className="form-actions"><button type="button" className="btn" onClick={onCancel}>Cancel</button><button className="btn primary" disabled={busy}>{busy?"Saving...":<><Save size={15}/> Save product</>}</button></div></form></div>
}

export default function AdminPanel(){
 const [products,setProducts]=useState<Product[]>([]),[editing,setEditing]=useState<Product|undefined>(),[creating,setCreating]=useState(false),[loading,setLoading]=useState(true),[msg,setMsg]=useState("");
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from("products").select("*").order("created_at",{ascending:false});if(error)setMsg(error.message);setProducts((data||[]) as Product[]);setLoading(false)};
 useEffect(()=>{load()},[]);
 const remove=async(p:Product)=>{if(!confirm("Delete this product?"))return;const {error}=await supabase.from("products").delete().eq("id",p.id);if(error)setMsg(error.message);else load()};
 return <section className="catalog-admin"><div className="catalog-head"><div><span className="eyebrow">Catalog management</span><h2>Products</h2></div><button className="btn primary" onClick={()=>setCreating(true)}><Plus size={15}/> Add product</button></div>{msg&&<div className="notice">{msg}</div>}{loading?<div className="notice">Loading products...</div>:<div className="admin-table"><table><thead><tr><th>Product</th><th>Price</th><th>Flags</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.title}</strong><small>{p.slug}</small></td><td>{p.currency} {Number(p.price).toFixed(2)}</td><td><span className={p.is_active?"status good":"status"}>{p.is_active?"Active":"Hidden"}</span>{p.is_deal&&<span className="status">Deal</span>}</td><td><div className="row-actions"><button onClick={()=>setEditing(p)} className="btn small">Edit</button><button onClick={()=>remove(p)} className="icon-danger" title="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!products.length&&<div className="empty">No products yet.</div>}</div>}{(creating||editing)&&<ProductForm initial={editing} onCancel={()=>{setCreating(false);setEditing(undefined)}} onSaved={()=>{setCreating(false);setEditing(undefined);load()}}/>}</section>
}
