import {useEffect,useMemo,useState} from "react";
import {supabase} from "./lib/supabase";
import AdminPanel from "./AdminPanel";
import type {Product,Category,Guide} from "./types";
import {ArrowRight,BookOpen,ExternalLink,Heart,LayoutDashboard,LogIn,Menu,Search,ShieldCheck,Sparkles,Tag,X} from "lucide-react";
import AdSlot from "./AdSlot";

const money=(n:number,c:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency:c||"USD"}).format(n);
const productImage=(p:Product)=>p.image_url||p.images?.[0]||"https://placehold.co/800x600/111827/ffffff?text="+encodeURIComponent(p.title.slice(0,24));
const readIds=(key:string)=>{try{return JSON.parse(localStorage.getItem(key)||"[]") as string[]}catch{return []}};
const saveIds=(key:string,ids:string[])=>localStorage.setItem(key,JSON.stringify(ids));

function Header({query,setQuery,savedCount,compareCount}:{query:string;setQuery:(v:string)=>void;savedCount:number;compareCount:number}){
 const [menu,setMenu]=useState(false);
 return <header className="header"><div className="container nav"><a className="brand" href="/"><span className="mark">A</span>Affinova</a><form className="search" onSubmit={e=>{e.preventDefault();document.getElementById("products")?.scrollIntoView({behavior:"smooth"})}}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></form><nav className={menu?"links open":"links"}><a href="#products">Products</a><a href="#deals">Deals</a><a href="#guides">Guides</a>{savedCount>0&&<a href="#saved">Saved ({savedCount})</a>}{compareCount>0&&<a href="#compare">Compare ({compareCount})</a>}<a href="/admin"><LayoutDashboard size={15}/> Admin</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div></header>;
}

function Card({p,saved,onSave,compared,onCompare}:{p:Product;saved:boolean;onSave:()=>void;compared:boolean;onCompare:()=>void}){
 return <article className="card"><a className="pic" href={"/product/"+p.slug}><img src={productImage(p)} alt={p.title}/>{p.is_deal&&<span className="badge"><Tag size={12}/> Deal</span>}</a><div className="card-body"><div className="rating">★ {Number(p.rating||0).toFixed(1)} <span>({p.review_count||0})</span></div><a className="title" href={"/product/"+p.slug}>{p.title}</a><div className="price"><strong>{money(Number(p.price),p.currency)}</strong>{p.original_price&&<><del>{money(Number(p.original_price),p.currency)}</del><span>-{p.discount_percentage}%</span></>}</div><div className="actions"><a className="btn dark" href={p.affiliate_url||"#"} target={p.affiliate_url?"_blank":undefined} rel="nofollow sponsored noopener">View deal <ExternalLink size={14}/></a><button className={"heart"+(saved?" saved":"")} aria-label={saved?"Remove from saved":"Save product"} onClick={onSave}><Heart size={17} fill={saved?"currentColor":"none"}/></button><button className={"compare-btn"+(compared?" active":"")} onClick={onCompare}>{compared?"Compared":"Compare"}</button></div></div></article>;
}

function CompareSection({products,onRemove}:{products:Product[];onRemove:(id:string)=>void}){
 if(!products.length)return null;
 return <section className="container section" id="compare"><div className="head"><div><span className="eyebrow">Side by side</span><h2>Compare products</h2></div><span className="muted">{products.length}/3 selected</span></div><div className="compare-wrap"><table className="compare-table"><thead><tr><th>Product</th>{products.map(p=><th key={p.id}><button className="remove-compare" onClick={()=>onRemove(p.id)} aria-label={"Remove "+p.title}><X size={14}/></button><img src={productImage(p)} alt=""/><a href={"/product/"+p.slug}>{p.title}</a></th>)}</tr></thead><tbody><tr><td>Price</td>{products.map(p=><td key={p.id}><strong>{money(Number(p.price),p.currency)}</strong></td>)}</tr><tr><td>Rating</td>{products.map(p=><td key={p.id}>★ {Number(p.rating||0).toFixed(1)}</td>)}</tr><tr><td>Reviews</td>{products.map(p=><td key={p.id}>{p.review_count||0}</td>)}</tr><tr><td>Deal</td>{products.map(p=><td key={p.id}>{p.is_deal?"Yes":"—"}</td>)}</tr></tbody></table></div></section>;
}

function Home(){
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[guides,setGuides]=useState<Guide[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true);
 const [savedIds,setSavedIds]=useState<string[]>([]),[compareIds,setCompareIds]=useState<string[]>([]);
 useEffect(()=>{setSavedIds(readIds("affinova_wishlist"));setCompareIds(readIds("affinova_compare"));(async()=>{const [p,c,g]=await Promise.all([supabase.from("products").select("*").eq("is_active",true).order("created_at",{ascending:false}),supabase.from("categories").select("*").eq("is_active",true).order("sort_order"),supabase.from("guides").select("*").eq("is_published",true).order("published_at",{ascending:false})]);setProducts((p.data||[]) as Product[]);setCategories((c.data||[]) as Category[]);setGuides((g.data||[]) as Guide[]);setLoading(false)})()},[]);
 const filtered=useMemo(()=>products.filter(p=>(p.title+" "+(p.brand||"")+" "+(p.tags||[]).join(" ")).toLowerCase().includes(query.toLowerCase())),[products,query]);
 const savedProducts=useMemo(()=>savedIds.map(id=>products.find(p=>p.id===id)).filter(Boolean) as Product[],[savedIds,products]);
 const compareProducts=useMemo(()=>compareIds.map(id=>products.find(p=>p.id===id)).filter(Boolean).slice(0,3) as Product[],[compareIds,products]);
 const toggleSave=(id:string)=>setSavedIds(prev=>{const next=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];saveIds("affinova_wishlist",next);return next});
 const toggleCompare=(id:string)=>setCompareIds(prev=>{if(prev.includes(id)){const next=prev.filter(x=>x!==id);saveIds("affinova_compare",next);return next}if(prev.length>=3){window.alert("You can compare up to 3 products.");return prev}const next=[...prev,id];saveIds("affinova_compare",next);return next});
 const removeCompare=(id:string)=>toggleCompare(id);
 return <><Header query={query} setQuery={setQuery} savedCount={savedProducts.length} compareCount={compareProducts.length}/><main><section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><Sparkles size={14}/> Curated product discovery</span><h1>Discover products <em>worth buying.</em></h1><p>Curated finds, useful gadgets, smart accessories and everyday products — all in one place.</p><div className="hero-actions"><a className="btn primary" href="#products">Explore products <ArrowRight size={16}/></a><a className="text-link" href="#guides">Buying guides →</a></div><div className="trust"><ShieldCheck size={16}/> Affiliate links may earn us a commission.</div></div><div className="hero-card"><div className="orb"/><small>SMART FINDS</small><strong>Less scrolling.<br/>Better choices.</strong><p>Affinova helps you discover useful products without the noise.</p></div></div></section><div className="container ad-container"><AdSlot slot={import.meta.env.VITE_ADSENSE_HOME_SLOT}/></div>
 <section className="container section"><div className="head"><div><span className="eyebrow">Browse</span><h2>Shop by category</h2></div></div><div className="categories">{categories.map(c=><a href="#products" onClick={()=>setQuery(c.name)} className="category" key={c.id}><b>{c.icon||"✦"}</b><strong>{c.name}</strong><small>{c.description||"Explore curated picks"}</small></a>)}</div></section>
 <section className="container section" id="products"><div className="head"><div><span className="eyebrow">Curated picks</span><h2>{query?("Results for “"+query+"”"):"Products worth a look"}</h2></div></div>{loading?<div className="grid">{[1,2,3,4].map(i=><div className="skeleton" key={i}/>)}</div>:filtered.length?<div className="grid">{filtered.slice(0,8).map(p=><Card p={p} key={p.id} saved={savedIds.includes(p.id)} onSave={()=>toggleSave(p.id)} compared={compareIds.includes(p.id)} onCompare={()=>toggleCompare(p.id)}/>)}</div>:<div className="empty">No matching products yet.</div>}</section>
 {savedProducts.length>0&&<section className="container section" id="saved"><div className="head"><div><span className="eyebrow">Your shortlist</span><h2>Saved products</h2></div></div><div className="grid">{savedProducts.map(p=><Card p={p} key={p.id} saved onSave={()=>toggleSave(p.id)} compared={compareIds.includes(p.id)} onCompare={()=>toggleCompare(p.id)}/>)}</div></section>}
 <CompareSection products={compareProducts} onRemove={removeCompare}/>
 <section className="dark-section" id="deals"><div className="container section"><div className="head light"><div><span className="eyebrow">Save more</span><h2>Highlighted deals</h2></div></div><div className="grid">{products.filter(p=>p.is_deal).slice(0,4).map(p=><Card p={p} key={p.id} saved={savedIds.includes(p.id)} onSave={()=>toggleSave(p.id)} compared={compareIds.includes(p.id)} onCompare={()=>toggleCompare(p.id)}/>)}</div></div></section>
 <section className="container section" id="guides"><div className="head"><div><span className="eyebrow">Learn before you buy</span><h2>Buying guides</h2></div></div><div className="guides">{guides.slice(0,6).map(g=><a className="guide" href={"/guide/"+g.slug} key={g.id}><div className="guide-cover">{g.cover_image?<img src={g.cover_image} alt=""/>:<BookOpen size={28}/>}</div><div><span>{g.category||"Guide"}</span><h3>{g.title}</h3><p>{g.excerpt||""}</p><b>Read guide <ArrowRight size={14}/></b></div></a>)}</div></section></main><footer><div className="container footer"><div><div className="brand"><span className="mark">A</span>Affinova</div><p>Product discovery, made simpler. We don't sell or ship products.</p></div><div><b>Explore</b><a href="#products">Products</a><a href="#deals">Deals</a><a href="#guides">Guides</a></div><div><b>Disclosure</b><p>Some links on Affinova are affiliate links. If you purchase through our links, we may earn a commission at no additional cost to you.</p></div></div><div className="bottom container">© {new Date().getFullYear()} Affinova</div></footer></main></>;
}
function Admin(){
 const [session,setSession]=useState<any>(null),[role,setRole]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const {data:{session}}=await supabase.auth.getSession();setSession(session);if(session?.user){const {data}=await supabase.from("profiles").select("role").eq("id",session.user.id).maybeSingle();setRole(data?.role||null)}};
 useEffect(()=>{load();const {data}=supabase.auth.onAuthStateChange(()=>load());return()=>data.subscription.unsubscribe()},[]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const {error}=await supabase.auth.signInWithPassword({email,password});setMessage(error?.message||"Signed in.")};
 if(!session)return <div className="admin-page"><div className="login"><a className="brand" href="/"><span className="mark">A</span>Affinova</a><h1>Admin sign in</h1><p>Use your Supabase account. Only users with the <b>admin</b> role can enter.</p><form onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn primary full"><LogIn size={15}/> Sign in</button></form>{message&&<div className="notice">{message}</div>}<a href="/">← Back to site</a></div></div>;
 if(role!=="admin")return <div className="admin-page"><div className="login"><ShieldCheck size={40}/><h1>Access denied</h1><p>This account is signed in but isn't an Affinova administrator.</p><button className="btn dark full" onClick={()=>supabase.auth.signOut()}>Sign out</button><a href="/">← Back to site</a></div></div>;
 return <div className="admin-shell"><aside><a className="brand" href="/"><span className="mark">A</span>Affinova</a><small>ADMIN</small><a className="side active" href="/admin"><LayoutDashboard size={16}/> Dashboard</a><a className="side" href="/#products">Products</a><a className="side" href="/#guides">Guides</a><button className="side" onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><section className="admin-main"><div className="admin-top"><div><span className="eyebrow">Control center</span><h1>Dashboard</h1></div><a className="btn dark" href="/">View site <ExternalLink size={14}/></a></div><div className="stats"><div><span>Signed in as</span><strong>{session.user.email}</strong></div><div><span>Role</span><strong>{role}</strong></div><div><span>Backend</span><strong>Supabase</strong></div></div><AdminPanel/></section></div>;
}
export default function App(){return location.pathname.startsWith("/admin")?<Admin/>:<Home/>}
