import React from "react";
import {ArrowLeft,Mail,ShieldCheck} from "lucide-react";

const Layout=({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode})=><div className="legal-page"><header className="legal-nav"><div className="container"><a className="brand" href="/"><span className="mark">A</span>Affinova</a><a className="back-link" href="/"><ArrowLeft size={15}/> Back to Affinova</a></div></header><main className="container legal-content"><span className="eyebrow">{kicker}</span><h1>{title}</h1>{children}</main><footer><div className="container bottom legal-bottom">© {new Date().getFullYear()} Affinova · <a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/affiliate-disclosure">Affiliate Disclosure</a> · <a href="/contact">Contact</a></div></footer></div>;

export function AboutPage(){return <Layout title="About Affinova" kicker="Why we exist"><p>Affinova is an independent product-discovery website built to make online shopping research simpler. Instead of asking you to scroll through endless listings, we curate useful products, highlight notable deals and publish practical buying guides.</p><h2>What we do</h2><p>We organize product ideas into clear categories, comparisons and guides so you can decide what is worth a closer look. Product information, prices and availability can change, so we encourage you to verify final details on the merchant's website.</p><h2>What we don't do</h2><p>Affinova does not manufacture, stock, sell or ship the products featured here. Purchases are completed on third-party merchant websites such as AliExpress, subject to their own terms, shipping policies and customer service.</p><h2>Affiliate transparency</h2><p>Some links are affiliate links. If you make a qualifying purchase after using one of our links, we may earn a commission at no additional cost to you. This relationship does not guarantee a product's inclusion.</p><h2>Our goal</h2><p>Less noise, clearer choices and useful information — that's what we're building with Affinova.</p></Layout>}

export function PrivacyPage(){return <Layout title="Privacy Policy" kicker="Your privacy"><p className="legal-updated">Last updated: October 7, 2026</p><h2>What we collect</h2><p>Affinova is a product-discovery website. We may receive information you voluntarily provide, such as an email when you contact us. We may also receive basic technical information such as browser type, device information, pages visited and approximate usage data through hosting, analytics or advertising services.</p><h2>How we use information</h2><p>We use information to operate and improve Affinova, respond to messages, understand site performance, prevent abuse and, where enabled, measure advertising and affiliate referrals.</p><h2>Cookies and local storage</h2><p>Affinova may use browser storage for features such as saved products and product comparisons. Advertising or analytics providers may use cookies or similar technologies according to their own policies. You can control cookies through your browser settings and available consent controls.</p><h2>Third-party links</h2><p>Product links may send you to third-party websites such as AliExpress. Their privacy practices are governed by their own policies, not this one.</p><h2>Contact</h2><p>If you have a privacy question, contact us through the <a className="legal-link" href="/contact">Contact page</a>.</p></Layout>}

export function TermsPage(){return <Layout title="Terms of Use" kicker="Site terms"><p className="legal-updated">Last updated: October 7, 2026</p><h2>Using Affinova</h2><p>Affinova provides product discovery, comparisons and buying guides for informational purposes. We do not sell, manufacture, warehouse or ship the products featured on the site.</p><h2>Prices and availability</h2><p>Prices, discounts, stock, shipping costs and availability can change on third-party stores at any time. Always confirm the final details on the merchant's website before purchasing.</p><h2>Affiliate relationships</h2><p>Some links are affiliate links. We may receive a commission if you make a qualifying purchase after clicking one of our links, at no additional cost to you.</p><h2>Content</h2><p>We aim to publish useful and accurate information, but we cannot guarantee that every description, price, rating or recommendation is complete, current or error-free.</p><h2>Third-party websites</h2><p>When you leave Affinova, you are subject to the destination website's terms and policies. We are not responsible for third-party sites or transactions.</p></Layout>}

export function AffiliatePage(){return <Layout title="Affiliate Disclosure" kicker="Transparency"><div className="disclosure-box"><ShieldCheck size={22}/><strong>Affinova uses affiliate links.</strong><p>When you click certain product links and make a qualifying purchase, we may earn a commission from the merchant. This does not increase the price you pay.</p></div><h2>How it works</h2><p>Affinova researches and curates products we believe may be useful. When a product has an affiliate relationship, the link may contain tracking information that lets the merchant attribute a qualifying purchase to us.</p><h2>Our approach</h2><p>Affiliate relationships do not guarantee that a product will be recommended. We aim to keep recommendations useful, clear and independent from the mechanics of the link.</p><h2>Merchant relationship</h2><p>Affinova is a product-discovery and affiliate website, not the seller. For orders, shipping, refunds, warranties and customer service, please contact the merchant directly.</p></Layout>}

export function ContactPage(){return <Layout title="Contact Affinova" kicker="Get in touch"><p>For questions, corrections, partnership inquiries or feedback, email the Affinova team.</p><a className="contact-card" href="mailto:hello@affinova.site"><Mail size={20}/><div><strong>hello@affinova.site</strong><span>General questions and feedback</span></div></a><p className="muted">If you are contacting us about a product, please include its Affinova page URL or product title so we can find it quickly.</p></Layout>}

export function NotFoundPage(){return <Layout title="Page not found" kicker="404"><p>The page you were looking for doesn't exist or may have moved.</p><a className="btn primary" href="/">Return to Affinova <ArrowLeft size={15}/></a></Layout>}
